#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot lead-time x threshold heatmaps of period-aggregated precipitation skill
scores for MONAN CTL and NEW.

Reads TXT files generated by precipitation_analysis_period_generate_skill_txt.py in:
    output/period_comparison_summary/<PERIOD>/Skill_txt_thr<THRESHOLD>mm/<PERIOD>/

Layout:
    rows: CTL, NEW
    cols: GPM, GSMaP, MSWEP

Metrics:
    ETS, CSI, POD, F1, F05, F2, ACC, POFD, FAR
"""

from __future__ import annotations

import argparse
import glob
import os
import re
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REGION_ANALYSIS = "REG"
REFERENCES = ("GPM", "GSMAP", "MSWEP")
EXPERIMENTS = ("CTL", "NEW")

METRICS = (
    "ETS",
    "CSI",
    "POD",
    "F1",
    "F05",
    "F2",
    "ACC",
    "POFD",
    "FAR",
)

DEFAULT_CMAP = "viridis"


def threshold_from_name(path):
    match = re.search(r"_thr([0-9]+(?:p[0-9]+)?)mm\.txt$", path)
    if not match:
        raise ValueError(f"Cannot extract threshold from filename: {path}")
    return float(match.group(1).replace("p", "."))


def get_metric_plot_config(df, metric):
    df_metric = df[
        (df["region"] == REGION_ANALYSIS)
        & (df["metric"] == metric)
    ]

    if df_metric.empty:
        raise ValueError(f"No data for metric {metric}")

    finite = df_metric.loc[np.isfinite(df_metric["value"]), "value"]

    if finite.empty:
        raise ValueError(f"No finite data for metric {metric}")

    vmax = np.ceil(float(finite.max()) * 10.0) / 10.0

    # ETS can legitimately be negative (worse than random).
    # Do not clip those values at zero.
    if metric == "ETS":
        vmin = min(
            0.0,
            np.floor(float(finite.min()) * 10.0) / 10.0,
        )
    else:
        vmin = 0.0

    if vmax <= vmin:
        vmax = vmin + 1.0

    return {
        "vmin": vmin,
        "vmax": vmax,
        "cmap": DEFAULT_CMAP,
    }


def parse_txt_file(file_path, period):
    name = os.path.basename(file_path)

    match = re.match(
        rf"Skill_(CTL|NEW)_{REGION_ANALYSIS}_"
        rf"{re.escape(period)}_thr([0-9]+(?:p[0-9]+)?)mm\.txt$",
        name,
    )

    if not match:
        return []

    experiment = match.group(1)
    threshold = threshold_from_name(file_path)

    with open(file_path, encoding="utf-8") as f:
        lines = f.readlines()

    start = None
    for i, line in enumerate(lines):
        if line.strip().startswith("LEAD"):
            start = i + 2
            break

    if start is None:
        return []

    records = []

    for line in lines[start:]:
        if not line.strip():
            continue

        parts = line.split()

        # LEAD REF ACC POD POFD FAR CSI F1 F05 F2 ETS
        if len(parts) < 11:
            continue

        lead = int(parts[0])
        reference = parts[1]

        values = {
            "ACC": float(parts[2]),
            "POD": float(parts[3]),
            "POFD": float(parts[4]),
            "FAR": float(parts[5]),
            "CSI": float(parts[6]),
            "F1": float(parts[7]),
            "F05": float(parts[8]),
            "F2": float(parts[9]),
            "ETS": float(parts[10]),
        }

        for metric, value in values.items():
            records.append(
                {
                    "experiment": experiment,
                    "region": REGION_ANALYSIS,
                    "reference": reference,
                    "threshold_mm": threshold,
                    "lead_h": lead,
                    "metric": metric,
                    "value": value,
                    "period": period,
                }
            )

    return records


def load_skill_dataframe(base_dir, period):
    pattern = str(
        base_dir
        / "output"
        / "period_comparison_summary"
        / period
        / "Skill_txt_thr*mm"
        / f"{period}"
        / f"Skill_*_{REGION_ANALYSIS}_{period}_thr*mm.txt"
    )

    files = glob.glob(pattern)
    records = []

    for file_path in files:
        records.extend(parse_txt_file(file_path, period))

    if not records:
        raise FileNotFoundError(
            "No TXT files found with pattern:\n"
            f"{pattern}"
        )

    return pd.DataFrame(records)


def choose_text_color(value, vmin, vmax):
    midpoint = (vmin + vmax) / 2.0
    if np.isfinite(value) and value < midpoint:
        return "white"
    return "black"


def plot_metric_2x3(df, period, metric, output_dir):
    cfg = get_metric_plot_config(df, metric)

    fig, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(16, 8.5),
        gridspec_kw={"hspace": 0.22, "wspace": 0.18},
    )

    last_im = None

    for row, experiment in enumerate(EXPERIMENTS):
        for col, reference in enumerate(REFERENCES):
            ax = axes[row, col]

            dfp = df[
                (df["region"] == REGION_ANALYSIS)
                & (df["metric"] == metric)
                & (df["experiment"] == experiment)
                & (df["reference"] == reference)
            ].copy()

            if dfp.empty:
                ax.set_axis_off()
                ax.text(
                    0.5, 0.5, "No data",
                    ha="center", va="center",
                    fontsize=12, transform=ax.transAxes
                )
                ax.set_title(f"{experiment} | {reference}", fontsize=11)
                continue

            table = dfp.pivot_table(
                index="lead_h",
                columns="threshold_mm",
                values="value",
            )

            table = table.sort_index().sort_index(axis=1)

            last_im = ax.imshow(
                table.values,
                origin="lower",
                aspect="auto",
                cmap=cfg["cmap"],
                vmin=cfg["vmin"],
                vmax=cfg["vmax"],
            )

            ax.set_xticks(range(len(table.columns)))
            ax.set_xticklabels(
                [
                    int(x) if float(x).is_integer() else x
                    for x in table.columns
                ]
            )

            ax.set_yticks(range(len(table.index)))
            ax.set_yticklabels(table.index.astype(int))

            if row == 1:
                ax.set_xlabel("Threshold (mm / 24 h)", fontsize=10)

            if col == 0:
                ax.set_ylabel("Forecast lead (h)", fontsize=10)

            ax.set_title(f"{experiment} | {reference}", fontsize=11)

            for i, lead in enumerate(table.index):
                for j, threshold in enumerate(table.columns):
                    value = table.loc[lead, threshold]

                    if np.isfinite(value):
                        ax.text(
                            j,
                            i,
                            f"{value:.2f}",
                            ha="center",
                            va="center",
                            fontsize=9,
                            color=choose_text_color(
                                value,
                                cfg["vmin"],
                                cfg["vmax"],
                            ),
                        )

    if last_im is not None:
        cbar = fig.colorbar(
            last_im,
            ax=axes,
            orientation="vertical",
            shrink=0.88,
            pad=0.02,
        )
        cbar.set_label(metric, fontsize=11)

    fig.suptitle(
        f"{metric} heatmap | CTL vs NEW | {REGION_ANALYSIS}\n"
        f"Initialization cycles: {period.replace('_', '–')}",
        fontsize=15,
        y=0.98,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    out = output_dir / (
        f"heatmap_{metric}_CTL_vs_NEW_{REGION_ANALYSIS}_{period}.png"
    )

    fig.savefig(
        out,
        dpi=200,
        bbox_inches="tight",
    )
    plt.close(fig)

    print(f"Figure saved: {out}")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start-cycle", required=True)
    parser.add_argument("--end-cycle", required=True)
    parser.add_argument(
        "--metrics",
        nargs="+",
        default=METRICS,
        choices=METRICS,
    )
    parser.add_argument(
        "--base-dir",
        default=str(Path(__file__).resolve().parent),
    )
    parser.add_argument("--output-dir", default=None)
    return parser.parse_args()


def main():
    args = parse_args()

    start = datetime.strptime(args.start_cycle, "%Y%m%d%H")
    end = datetime.strptime(args.end_cycle, "%Y%m%d%H")

    if end < start:
        raise ValueError("end-cycle must be >= start-cycle.")

    base_dir = Path(args.base_dir).resolve()
    period = f"{args.start_cycle}_{args.end_cycle}"

    output_dir = (
        Path(args.output_dir).resolve()
        if args.output_dir
        else (
            base_dir
            / "output"
            / "period_comparison_figures"
            / period
            / "Skill_heatmap"
        )
    )

    df = load_skill_dataframe(
        base_dir=base_dir,
        period=period,
    )

    for metric in args.metrics:
        plot_metric_2x3(
            df=df,
            period=period,
            metric=metric,
            output_dir=output_dir,
        )

    print("Skill heatmaps generated successfully.")


if __name__ == "__main__":
    main()
