#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: André Lyra <andre.lyra@inpe.br>

"""
This script calculates the Fractions Skill Score (FSS) for 24-hour
accumulated precipitation from MONAN experiments.

The forecast precipitation fields are read from the 24-hour accumulated
precipitation files previously generated by the precipitation analysis.

The observational references are read from files already conservatively
remapped to the grid of each MONAN experiment. No additional remapping
is performed in this script.

Examples:

    python Calc_FSS_MONAN_CTL_NEW.py

    python Calc_FSS_MONAN_CTL_NEW.py \
        --experiments MONAN_CTL_AMS_CAR

    python Calc_FSS_MONAN_CTL_NEW.py \
        --experiments MONAN_CTL_AMS_CAR MONAN_NEW_AMS_CAR \
        --references GPM MSWEP
"""

import argparse
import csv
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import xarray as xr

import monan_analysis.stats as stats
import monan_analysis.preprocess as preprocess


# Configuration

# Input directories
BASE_PRECIP = Path("../../analyses/precipitation/precip_24h")
BASE_REFERENCE = Path("../../analyses/precipitation/input")
# Output directory
OUTDIR_FSS = Path("FSS_results_CTL_x_NEW_x_NEW2")

# One or more experiments to process
EXPERIMENTS = [
    "MONAN_CTL_AMS_CAR",
    "MONAN_NEW_AMS_CAR",
    "MONAN_NEW2_AMS_CAR",
]

# One or more observational references to process
REFERENCES = [
    "GPM",
    "GSMAP",
    "MSWEP",
]

# List of cycles to process
CYCLES = [
    "2026010100",
    "2026010200",
    "2026010300",
    "2026010400",
    "2026010500",
    "2026010600",
    "2026010700",
    "2026010800",
    "2026010900",
    "2026011000",
]

# List of lead times (in hours) to process
LEADS = [
    24,
    48,
    72,
    96,
    120,
]

# List of precipitation thresholds (in mm) to process
THRESHOLDS = [
    1,
    2,
    5,
    10,
    20,
    50,
]

# List of window sizes (in grid points) to process
WINDOW_SIZES = [
    1,
    3,
    5,
    9,
    15,
    25,
]

VAR_PREC = "prec"

EARTH_KM_PER_DEGREE = 111.32

# Argument parser for command-line options.
def parse_args():

    parser = argparse.ArgumentParser(
        description=(
            "Calculates FSS for the MONAN controle and "
            "MONAN experiments."
        )
    )

    parser.add_argument(
        "--experiments",
        nargs="+",
        default=["all"],
        help=(
            "Experiments to process. Use variables defined in EXPERIMENTS, "
            "Default: all."
        ),
    )

    parser.add_argument(
        "--references",
        nargs="+",
        default=["all"],
        help=(
            "References to process. Use GPM, GSMAP, MSWEP, "
            "or all. Default: all."
        ),
    )

    return parser.parse_args()


def seleciona_opcoes(escolhas, disponiveis, nome):

    mapa = {
        str(item).lower(): item
        for item in disponiveis
    }

    escolhas_lower = [
        item.lower()
        for item in escolhas
    ]

    if "all" in escolhas_lower:
        return list(disponiveis)

    invalidas = [
        item
        for item in escolhas_lower
        if item not in mapa
    ]

    if invalidas:
        raise ValueError(
            f"{nome} inválido(s): {invalidas}. "
            f"Opções disponíveis: {list(disponiveis)}"
        )

    return [
        mapa[item]
        for item in escolhas_lower
    ]


# Input files

# Locates the 24-hour accumulated forecast precipitation file.
def caminho_previsao(experimento, ciclo, lead):

    data_inicial = datetime.strptime(
        ciclo,
        "%Y%m%d%H",
    )

    data_valida = data_inicial + timedelta(
        hours=int(lead)
    )

    valid_str = data_valida.strftime("%Y%m%d%H")
    lead_str = f"{int(lead):03d}h"

    nome = (
        f"MONAN_Precipitation_24h_acum_"
        f"{ciclo}_{valid_str}_{lead_str}.nc"
    )

    return (
        BASE_PRECIP
        / experimento
        / ciclo
        / nome
    )


# Locates the observational reference already conservatively remapped
# to the grid of the corresponding MONAN experiment.
def caminho_referencia(referencia, experimento, ciclo, lead):

    data_inicial = datetime.strptime(
        ciclo,
        "%Y%m%d%H",
    )

    data_valida = data_inicial + timedelta(
        hours=int(lead)
    )

    valid_str = data_valida.strftime("%Y%m%d%H")

    nome = (
        f"{referencia}_{valid_str}_"
        f"{experimento}_grid.nc"
    )

    return (
        BASE_REFERENCE
        / experimento
        / "processed"
        / ciclo
        / nome
    )


# Normalizes coordinate names to 'lat' and 'lon'.
def normaliza_nomes_coordenadas(da):

    renomear = {}

    if "latitude" in da.dims or "latitude" in da.coords:
        renomear["latitude"] = "lat"

    if "longitude" in da.dims or "longitude" in da.coords:
        renomear["longitude"] = "lon"

    if renomear:
        da = da.rename(renomear)

    if "lat" not in da.coords or "lon" not in da.coords:
        raise ValueError(
            "The field does not contain lat/lon coordinates."
        )

    if da["lat"].ndim != 1 or da["lon"].ndim != 1:
        raise ValueError(
            "This script requires one-dimensional latitude "
            "and longitude coordinates."
        )

    return da


# Prepares the precipitation field by opening the NetCDF.
def prepara_precipitacao(path):

    with xr.open_dataset(path) as ds:

        if VAR_PREC not in ds:
            raise KeyError(
                f"Variable '{VAR_PREC}' not found in {path}. "
                f"Available variables: {list(ds.data_vars)}"
            )

        da = ds[VAR_PREC].squeeze(drop=True).load()

    da = normaliza_nomes_coordenadas(da)

    da = da.where(np.isfinite(da))

    # Negative accumulated precipitation is treated as zero.
    da = xr.where(
        np.isfinite(da) & (da < 0.0),
        0.0,
        da,
    )

    da = da.sortby("lat")
    da = da.sortby("lon")

    da = da.transpose("lat", "lon")

    return da


# Checks if two fields have exactly the same grid within tolerance.
def grades_iguais(campo_a, campo_b, atol=1.0e-6):

    mesma_forma = campo_a.shape == campo_b.shape

    mesmas_latitudes = (
        campo_a.sizes["lat"] == campo_b.sizes["lat"]
        and np.allclose(
            campo_a["lat"].values,
            campo_b["lat"].values,
            rtol=0.0,
            atol=atol,
            equal_nan=True,
        )
    )

    mesmas_longitudes = (
        campo_a.sizes["lon"] == campo_b.sizes["lon"]
        and np.allclose(
            campo_a["lon"].values,
            campo_b["lon"].values,
            rtol=0.0,
            atol=atol,
            equal_nan=True,
        )
    )

    return (
        mesma_forma
        and mesmas_latitudes
        and mesmas_longitudes
    )


# Confirms that forecast and reference are on the same grid.
def alinha_campos(fcst, obs):

    if not grades_iguais(fcst, obs):
        raise ValueError(
            "Forecast and reference are not on the same grid. "
            f"Forecast={fcst.shape}; reference={obs.shape}."
        )

    obs = obs.assign_coords(
        lat=fcst["lat"],
        lon=fcst["lon"],
    )

    return fcst, obs


# Calculates latitude weights for area-weighted averaging.
def pesos_latitude(da):

    weights = np.cos(
        np.deg2rad(da["lat"])
    )

    return xr.DataArray(
        weights,
        coords={"lat": da["lat"]},
        dims=["lat"],
    )


# Estimates the grid resolution and corresponding distance.
def estima_resolucao_grade(da):

    lat_values = np.asarray(
        da["lat"].values,
        dtype="float64",
    )

    lon_values = np.asarray(
        da["lon"].values,
        dtype="float64",
    )

    if lat_values.size < 2 or lon_values.size < 2:
        return {
            "grid_dlat_deg": np.nan,
            "grid_dlon_deg": np.nan,
            "grid_dy_km": np.nan,
            "grid_dx_km": np.nan,
            "representative_lat": np.nan,
        }

    dlat = float(
        np.nanmedian(
            np.abs(np.diff(lat_values))
        )
    )

    dlon = float(
        np.nanmedian(
            np.abs(np.diff(lon_values))
        )
    )

    representative_lat = float(
        np.nanmedian(lat_values)
    )

    dy_km = (
        EARTH_KM_PER_DEGREE
        * dlat
    )

    dx_km = (
        EARTH_KM_PER_DEGREE
        * dlon
        * np.cos(
            np.deg2rad(representative_lat)
        )
    )

    return {
        "grid_dlat_deg": dlat,
        "grid_dlon_deg": dlon,
        "grid_dy_km": dy_km,
        "grid_dx_km": dx_km,
        "representative_lat": representative_lat,
    }


# Creates accumulators for all combinations of lead time,
# threshold, and window size.
def cria_acumuladores():

    acumuladores = {}

    for lead in LEADS:
        for threshold in THRESHOLDS:
            for window_size in WINDOW_SIZES:

                chave = (
                    int(lead),
                    float(threshold),
                    int(window_size),
                )

                acumuladores[chave] = {
                    "fbs_sum": 0.0,
                    "fbs_worst_sum": 0.0,
                    "n_valid_cases": 0,
                    "n_missing_pairs": 0,
                    "n_processing_errors": 0,
                    "n_no_event_cases": 0,
                    "grid_dlat_deg": np.nan,
                    "grid_dlon_deg": np.nan,
                    "grid_dy_km": np.nan,
                    "grid_dx_km": np.nan,
                    "representative_lat": np.nan,
                }

    return acumuladores


# Calculates FSS for one experiment and one observational reference.
def calcula_combinacao(experimento, referencia):

    linhas_casos = []

    acumuladores = cria_acumuladores()

    print()
    print("=" * 80)
    print(
        f"Calculating FSS: "
        f"{experimento} vs {referencia}"
    )
    print(
        "Observational reference already remapped "
        "conservatively to the experiment grid."
    )
    print(
        "No additional remapping is performed."
    )
    print("=" * 80)

    for ciclo in CYCLES:

        print()
        print(f"Cycle {ciclo}")

        data_inicial = datetime.strptime(
            ciclo,
            "%Y%m%d%H",
        )

        for lead in LEADS:

            data_valida = (
                data_inicial
                + timedelta(hours=int(lead))
            )

            valid_str = data_valida.strftime(
                "%Y%m%d%H"
            )

            forecast_file = caminho_previsao(
                experimento=experimento,
                ciclo=ciclo,
                lead=lead,
            )

            reference_file = caminho_referencia(
                referencia=referencia,
                experimento=experimento,
                ciclo=ciclo,
                lead=lead,
            )

            forecast_missing = (
                not forecast_file.exists()
            )

            reference_missing = (
                not reference_file.exists()
            )

            if forecast_missing or reference_missing:

                print(
                    f"  {valid_str} "
                    f"lead={lead:03d}h: "
                    "missing input file"
                )

                for threshold in THRESHOLDS:
                    for window_size in WINDOW_SIZES:

                        chave = (
                            int(lead),
                            float(threshold),
                            int(window_size),
                        )

                        acumuladores[chave][
                            "n_missing_pairs"
                        ] += 1

                continue

            try:

                fcst = prepara_precipitacao(
                    forecast_file
                )

                obs = prepara_precipitacao(
                    reference_file
                )

                fcst, obs = alinha_campos(
                    fcst,
                    obs,
                )

                resolucao = estima_resolucao_grade(
                    fcst
                )

                weights = pesos_latitude(
                    fcst
                )

                # Regional domain, therefore longitude is not periodic.
                boundary_modes = (
                    "constant",
                    "constant",
                )

                valid_mask = (
                    np.isfinite(fcst)
                    & np.isfinite(obs)
                )

                for threshold in THRESHOLDS:

                    fcst_event = (
                        preprocess.threshold_event(
                            data=fcst,
                            threshold=float(threshold),
                            comparison="ge",
                            valid_mask=valid_mask,
                        )
                    )

                    obs_event = (
                        preprocess.threshold_event(
                            data=obs,
                            threshold=float(threshold),
                            comparison="ge",
                            valid_mask=valid_mask,
                        )
                    )

                    for window_size in WINDOW_SIZES:

                        fss, fbs, fbs_worst = (
                            stats.fractions_skill_score(
                                forecast_event=fcst_event,
                                observation_event=obs_event,
                                window_size=int(
                                    window_size
                                ),
                                spatial_dims=(
                                    "lat",
                                    "lon",
                                ),
                                boundary_modes=(
                                    boundary_modes
                                ),
                                weights=weights,
                            )
                        )

                        chave = (
                            int(lead),
                            float(threshold),
                            int(window_size),
                        )

                        acc = acumuladores[chave]

                        for campo, valor in (
                            resolucao.items()
                        ):
                            acc[campo] = valor

                        window_lat_km = (
                            int(window_size)
                            * resolucao["grid_dy_km"]
                        )

                        window_lon_km = (
                            int(window_size)
                            * resolucao["grid_dx_km"]
                        )

                        status = "ok"

                        if np.isfinite(fss):

                            acc["fbs_sum"] += fbs

                            acc[
                                "fbs_worst_sum"
                            ] += fbs_worst

                            acc[
                                "n_valid_cases"
                            ] += 1

                        else:

                            status = "no_event"

                            acc[
                                "n_no_event_cases"
                            ] += 1

                        linhas_casos.append({
                            "experiment": experimento,
                            "reference": referencia,
                            "cycle": ciclo,
                            "valid_date": valid_str,
                            "lead": int(lead),
                            "threshold_mm": float(
                                threshold
                            ),
                            "window_points": int(
                                window_size
                            ),
                            "window_lat_km": (
                                window_lat_km
                            ),
                            "window_lon_km": (
                                window_lon_km
                            ),
                            "grid_dlat_deg": (
                                resolucao[
                                    "grid_dlat_deg"
                                ]
                            ),
                            "grid_dlon_deg": (
                                resolucao[
                                    "grid_dlon_deg"
                                ]
                            ),
                            "grid_dy_km": (
                                resolucao[
                                    "grid_dy_km"
                                ]
                            ),
                            "grid_dx_km": (
                                resolucao[
                                    "grid_dx_km"
                                ]
                            ),
                            "representative_lat": (
                                resolucao[
                                    "representative_lat"
                                ]
                            ),
                            "fss": fss,
                            "fbs": fbs,
                            "fbs_worst": fbs_worst,
                            "status": status,
                            "forecast_file": str(
                                forecast_file
                            ),
                            "reference_file": str(
                                reference_file
                            ),
                        })

                print(
                    f"  {valid_str} "
                    f"lead={lead:03d}h: processed"
                )

            except Exception as erro:

                for threshold in THRESHOLDS:
                    for window_size in WINDOW_SIZES:

                        chave = (
                            int(lead),
                            float(threshold),
                            int(window_size),
                        )

                        acumuladores[chave][
                            "n_processing_errors"
                        ] += 1

                print(
                    f"  Error in cycle {ciclo}, "
                    f"valid={valid_str}, "
                    f"lead={lead:03d}h: {erro}"
                )

    linhas_agregadas = []

    for chave, acc in acumuladores.items():

        lead, threshold, window_size = chave

        if (
            acc["n_valid_cases"] > 0
            and acc["fbs_worst_sum"] > 0.0
        ):
            fss_agregado = 1.0 - (
                acc["fbs_sum"]
                / acc["fbs_worst_sum"]
            )
        else:
            fss_agregado = np.nan

        window_lat_km = (
            window_size
            * acc["grid_dy_km"]
            if np.isfinite(
                acc["grid_dy_km"]
            )
            else np.nan
        )

        window_lon_km = (
            window_size
            * acc["grid_dx_km"]
            if np.isfinite(
                acc["grid_dx_km"]
            )
            else np.nan
        )

        linhas_agregadas.append({
            "experiment": experimento,
            "reference": referencia,
            "lead": lead,
            "threshold_mm": threshold,
            "window_points": window_size,
            "window_lat_km": window_lat_km,
            "window_lon_km": window_lon_km,
            "grid_dlat_deg": acc[
                "grid_dlat_deg"
            ],
            "grid_dlon_deg": acc[
                "grid_dlon_deg"
            ],
            "grid_dy_km": acc[
                "grid_dy_km"
            ],
            "grid_dx_km": acc[
                "grid_dx_km"
            ],
            "representative_lat": acc[
                "representative_lat"
            ],
            "fss": fss_agregado,
            "fbs_sum": acc[
                "fbs_sum"
            ],
            "fbs_worst_sum": acc[
                "fbs_worst_sum"
            ],
            "n_valid_cases": acc[
                "n_valid_cases"
            ],
            "n_missing_pairs": acc[
                "n_missing_pairs"
            ],
            "n_processing_errors": acc[
                "n_processing_errors"
            ],
            "n_no_event_cases": acc[
                "n_no_event_cases"
            ],
            "n_expected_cases": len(CYCLES),
        })

        fss_texto = (
            f"{fss_agregado:.3f}"
            if np.isfinite(fss_agregado)
            else "nan"
        )

        print(
            f"{experimento} vs {referencia} "
            f"lead={lead:03d}h "
            f"thr={threshold:g}mm "
            f"window={window_size} "
            f"FSS={fss_texto} "
            f"n={acc['n_valid_cases']}"
        )

    return (
        linhas_casos,
        linhas_agregadas,
    )


# Output

# Saves a list of dictionaries to a CSV file.
def salva_csv(linhas, path):

    if not linhas:
        print(
            f"No rows to save in {path}"
        )
        return

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    campos = list(
        linhas[0].keys()
    )

    with open(
        path,
        "w",
        newline="",
        encoding="utf-8",
    ) as arquivo:

        writer = csv.DictWriter(
            arquivo,
            fieldnames=campos,
        )

        writer.writeheader()

        writer.writerows(linhas)


# Main
def main():

    args = parse_args()

    experimentos = seleciona_opcoes(
        args.experiments,
        EXPERIMENTS,
        "Experiment",
    )

    referencias = seleciona_opcoes(
        args.references,
        REFERENCES,
        "Reference",
    )

    period_start = datetime.strptime(
        min(CYCLES),
        "%Y%m%d%H",
    ).strftime("%Y%m%d")

    period_end = datetime.strptime(
        max(CYCLES),
        "%Y%m%d%H",
    ).strftime("%Y%m%d")

    for experimento in experimentos:

        for referencia in referencias:

            linhas_casos, linhas_agregadas = (
                calcula_combinacao(
                    experimento=experimento,
                    referencia=referencia,
                )
            )

            outdir_combinacao = (
                OUTDIR_FSS
                / experimento
                / referencia
            )

            csv_casos = (
                outdir_combinacao
                / (
                    f"FSS_cases_{experimento}_vs_"
                    f"{referencia}_{period_start}_{period_end}.csv"
                )
            )

            csv_agregado = (
                outdir_combinacao
                / (
                    f"FSS_aggregate_{experimento}_vs_"
                    f"{referencia}_{period_start}_{period_end}.csv"
                )
            )

            salva_csv(
                linhas=linhas_casos,
                path=csv_casos,
            )

            salva_csv(
                linhas=linhas_agregadas,
                path=csv_agregado,
            )

            print()
            print(
                f"Case CSV saved in: {csv_casos}"
            )
            print(
                f"Aggregate CSV saved in: "
                f"{csv_agregado}"
            )


if __name__ == "__main__":
    main()