#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Plot FSS comparison between MONAN_CTL_AMS_CAR and MONAN_NEW_AMS_CAR.
#
# Input:
#   FSS_results_CTL_x_NEW/
#       MONAN_CTL_AMS_CAR/{REFERENCE}/FSS_aggregate_*.csv
#       MONAN_NEW_AMS_CAR/{REFERENCE}/FSS_aggregate_*.csv
#
# Main outputs for each observational reference:
#   1) CTL x NEW FSS panels
#   2) Delta FSS panels: NEW - CTL
#
# The script does not perform remapping or recalculate FSS.
# It only reads the aggregate CSV files generated by
# Calc_FSS_MONAN_CTL_NEW.py.
#
# Author: Andre Lyra
#

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, TwoSlopeNorm
import numpy as np
import pandas as pd


# Configuration
# Input directory
BASE_FSS = Path("FSS_results_CTL_x_NEW_x_NEW2")
# Output directory
OUTDIR_FIG = Path("FSS_Figures_CTL_x_NEW_x_NEW2")

# Always compare two experiments
EXPERIMENT_CTL = "MONAN_NEW_AMS_CAR"
EXPERIMENT_NEW = "MONAN_NEW2_AMS_CAR"

# Short labels used in figure titles and panel headers.
EXPERIMENT_CTL_LABEL = "NEW"
EXPERIMENT_NEW_LABEL = "NEW2"

REFERENCES = ["GPM", "GSMAP", "MSWEP"]

LEADS = [24, 48, 72, 96, 120]

THRESHOLDS = [1, 2, 5, 10, 20, 50]

WINDOW_SIZES = [1, 3, 5, 9, 15, 25]

# FSS scale
FSS_LEVELS = np.arange(0.0, 1.05, 0.05)

CMAP_FSS = plt.get_cmap(
    "RdYlGn",
    len(FSS_LEVELS) - 1,
)

NORM_FSS = BoundaryNorm(
    FSS_LEVELS,
    ncolors=CMAP_FSS.N,
    clip=True,
)

FSS_REFERENCE_LEVEL = 0.5

CMAP_DELTA = "RdBu_r"

# Symmetric Delta FSS colour scale.
# Fixed range can be set or None to determine automatically
DELTA_LIMIT = 0.10

DPI = 150

# Command-line arguments
def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Plot FSS comparison between MONAN controle and "
            "MONAN experiments."
        )
    )

    parser.add_argument(
        "--references",
        nargs="+",
        default=["all"],
        choices=REFERENCES + ["all"],
        help=(
            "Observational references to plot. "
            "Options: GPM GSMAP MSWEP all"
        ),
    )

    parser.add_argument(
        "--base-dir",
        default=str(BASE_FSS),
        help=(
            "Directory containing FSS_results_CTL_x_NEW. "
            f"Default: {BASE_FSS}"
        ),
    )

    parser.add_argument(
        "--output-dir",
        default=str(OUTDIR_FIG),
        help=(
            "Directory where figures will be saved. "
            f"Default: {OUTDIR_FIG}"
        ),
    )

    return parser.parse_args()


# Auxiliary functions
def select_references(requested):
    """Return the list of references selected on the command line."""

    if "all" in requested:
        return REFERENCES.copy()

    return requested


def find_aggregate_file(base_dir, experiment, reference):
    """
    Locate the aggregate CSV for one experiment/reference pair.

    Exactly one file is expected.
    """

    directory = (
        Path(base_dir)
        / experiment
        / reference
    )

    pattern = (
        f"FSS_aggregate_{experiment}_vs_{reference}_*.csv"
    )

    files = sorted(directory.glob(pattern))

    if len(files) == 0:
        raise FileNotFoundError(
            f"No aggregate CSV found for "
            f"{experiment} vs {reference} in {directory}"
        )

    if len(files) > 1:
        raise RuntimeError(
            f"More than one aggregate CSV found for "
            f"{experiment} vs {reference}:\n"
            + "\n".join(str(f) for f in files)
        )

    return files[0]


def read_aggregate_csv(filename):
    """Read and perform basic validation of an aggregate FSS CSV."""

    df = pd.read_csv(filename)

    required_columns = {
        "experiment",
        "reference",
        "lead",
        "threshold_mm",
        "window_points",
        "window_lat_km",
        "window_lon_km",
        "fss",
        "n_valid_cases",
        "n_missing_pairs",
        "n_processing_errors",
        "n_no_event_cases",
        "n_expected_cases",
    }

    missing = required_columns - set(df.columns)

    if missing:
        raise ValueError(
            f"{filename} is missing required columns: "
            f"{sorted(missing)}"
        )

    return df


def validate_expected_structure(df, experiment, reference):
    """
    Validate the expected lead x threshold x window structure.

    This validation does not modify the data.
    """

    expected_rows = (
        len(LEADS)
        * len(THRESHOLDS)
        * len(WINDOW_SIZES)
    )

    if len(df) != expected_rows:
        raise ValueError(
            f"{experiment} vs {reference}: "
            f"expected {expected_rows} rows, found {len(df)}."
        )

    leads_found = sorted(df["lead"].unique().tolist())
    thresholds_found = sorted(
        df["threshold_mm"].unique().tolist()
    )
    windows_found = sorted(
        df["window_points"].unique().tolist()
    )

    if leads_found != LEADS:
        raise ValueError(
            f"{experiment} vs {reference}: "
            f"unexpected leads: {leads_found}"
        )

    if thresholds_found != THRESHOLDS:
        raise ValueError(
            f"{experiment} vs {reference}: "
            f"unexpected thresholds: {thresholds_found}"
        )

    if windows_found != WINDOW_SIZES:
        raise ValueError(
            f"{experiment} vs {reference}: "
            f"unexpected window sizes: {windows_found}"
        )

    duplicated = df.duplicated(
        subset=[
            "lead",
            "threshold_mm",
            "window_points",
        ]
    )

    if duplicated.any():
        raise ValueError(
            f"{experiment} vs {reference}: "
            "duplicated lead/threshold/window combinations found."
        )


def validate_processing_status(df, experiment, reference):
    """
    Check processing diagnostics stored in the aggregate CSV.

    Missing pairs and processing errors are treated as errors because
    CTL and NEW must be compared using equivalent samples.
    """

    if (df["n_missing_pairs"] != 0).any():
        raise ValueError(
            f"{experiment} vs {reference}: "
            "n_missing_pairs is not zero."
        )

    if (df["n_processing_errors"] != 0).any():
        raise ValueError(
            f"{experiment} vs {reference}: "
            "n_processing_errors is not zero."
        )

    if (
        df["n_valid_cases"]
        != df["n_expected_cases"]
    ).any():
        raise ValueError(
            f"{experiment} vs {reference}: "
            "n_valid_cases differs from n_expected_cases."
        )


def prepare_comparison(df_ctl, df_new, reference):
    """
    Match CTL and NEW using exactly the same
    lead/threshold/window combinations.

    Returns a DataFrame containing:
        fss_ctl
        fss_new
        delta_fss = fss_new - fss_ctl
    """

    keys = [
        "reference",
        "lead",
        "threshold_mm",
        "window_points",
    ]

    ctl = df_ctl.sort_values(keys).reset_index(drop=True)
    new = df_new.sort_values(keys).reset_index(drop=True)

    ctl_keys = ctl[keys]
    new_keys = new[keys]

    try:
        pd.testing.assert_frame_equal(
            ctl_keys,
            new_keys,
            check_dtype=False,
        )
    except AssertionError as exc:
        raise ValueError(
            f"CTL and NEW do not contain the same "
            f"lead/threshold/window combinations for {reference}."
        ) from exc

    if not np.array_equal(
        ctl["n_valid_cases"].to_numpy(),
        new["n_valid_cases"].to_numpy(),
    ):
        raise ValueError(
            f"CTL and NEW have different numbers of valid cases "
            f"for {reference}."
        )

    grid_columns = [
        "grid_dlat_deg",
        "grid_dlon_deg",
        "grid_dy_km",
        "grid_dx_km",
        "window_lat_km",
        "window_lon_km",
    ]

    for column in grid_columns:
        if not np.allclose(
            ctl[column].to_numpy(),
            new[column].to_numpy(),
            rtol=0.0,
            atol=1.0e-6,
            equal_nan=True,
        ):
            raise ValueError(
                f"{column} differs between "
                f"{EXPERIMENT_CTL_LABEL} and {EXPERIMENT_NEW_LABEL}. "
                "FSS values based on the same window_points would not "
                "represent the same physical spatial scale."
            )

    comparison = ctl[
        [
            "reference",
            "lead",
            "threshold_mm",
            "window_points",
            "window_lat_km",
            "window_lon_km",
            "n_valid_cases",
        ]
    ].copy()

    comparison["fss_ctl"] = ctl["fss"].to_numpy()
    comparison["fss_new"] = new["fss"].to_numpy()

    comparison["delta_fss"] = (
        comparison["fss_new"]
        - comparison["fss_ctl"]
    )

    return comparison


def make_matrix(df, threshold, value_column):
    """
    Create a window x lead matrix for one precipitation threshold.
    """

    subset = df[
        np.isclose(
            df["threshold_mm"].astype(float),
            float(threshold),
        )
    ].copy()

    matrix = subset.pivot(
        index="window_points",
        columns="lead",
        values=value_column,
    )

    matrix = matrix.reindex(
        index=WINDOW_SIZES,
        columns=LEADS,
    )

    return matrix


def format_threshold(threshold):
    """Format threshold for panel titles."""

    if float(threshold).is_integer():
        return f"{int(threshold)}"

    return f"{threshold:g}"


def get_window_labels(df):
    """
    Build y-axis labels using grid points and the approximate
    meridional physical scale already stored in the CSV.

    No new conversion from grid points to kilometres is performed here.
    """

    labels = []

    for window in WINDOW_SIZES:

        subset = df[
            df["window_points"] == window
        ]

        if subset.empty:
            labels.append(f"{window} pts")
            continue

        km_values = subset["window_lat_km"].dropna().to_numpy()

        if km_values.size == 0:
            labels.append(f"{window} pts")
            continue

        km = float(np.nanmedian(km_values))

        labels.append(
            f"{window} pts (~{km:.0f} km)"
        )

    return labels

def draw_step_boundary(
    ax,
    z_values,
    threshold=0.5,
    color="black",
    linewidth=0.75,
):
    """
    Draw a stepped boundary separating cells below and above
    the selected FSS threshold.

    Cells with FSS >= threshold are considered above the boundary.
    """

    valid = np.isfinite(z_values)

    if not np.any(valid):
        return

    mask = np.zeros_like(z_values, dtype=bool)
    mask[valid] = z_values[valid] >= threshold

    nrows, ncols = mask.shape

    # Vertical boundaries between adjacent columns.
    for row in range(nrows):
        for col in range(ncols - 1):

            if not (
                valid[row, col]
                and valid[row, col + 1]
            ):
                continue

            if mask[row, col] != mask[row, col + 1]:

                x = col + 0.5

                ax.plot(
                    [x, x],
                    [row - 0.5, row + 0.5],
                    color=color,
                    linewidth=linewidth,
                    linestyle="--",
                )

    # Horizontal boundaries between adjacent rows.
    for row in range(nrows - 1):
        for col in range(ncols):

            if not (
                valid[row, col]
                and valid[row + 1, col]
            ):
                continue

            if mask[row, col] != mask[row + 1, col]:

                y = row + 0.5

                ax.plot(
                    [col - 0.5, col + 0.5],
                    [y, y],
                    color=color,
                    linewidth=linewidth,
                    linestyle="--",
                )

# Plot 1: CTL x NEW
def plot_ctl_new(comparison, reference, output_dir):
    """
    Plot absolute FSS for CTL and NEW.

    Rows:
        precipitation thresholds

    Columns:
        CTL and NEW

    Both experiments use exactly the same FSS colour scale.
    """

    fig, axes = plt.subplots(
        nrows=len(THRESHOLDS),
        ncols=2,
        figsize=(13, 20),
        sharex=True,
        sharey=True,
        constrained_layout=False,
    )

    window_labels = get_window_labels(comparison)

    last_im = None

    experiment_columns = [
        ("fss_ctl", EXPERIMENT_CTL_LABEL),
        ("fss_new", EXPERIMENT_NEW_LABEL),
    ]

    for row, threshold in enumerate(THRESHOLDS):

        for col, (value_column, experiment_label) in enumerate(
            experiment_columns
        ):

            ax = axes[row, col]

            matrix = make_matrix(
                comparison,
                threshold,
                value_column,
            )

            last_im = ax.imshow(
                matrix.to_numpy(),
                origin="lower",
                aspect="auto",
                cmap=CMAP_FSS,
                norm=NORM_FSS,
                interpolation="nearest",
            )

            # FSS = 0.5 contour.
            draw_step_boundary(
                ax,
                matrix.to_numpy(),
                threshold=FSS_REFERENCE_LEVEL,
                color="black",
                linewidth=0.75,
            )

            ax.set_xticks(
                np.arange(len(LEADS))
            )

            ax.set_xticklabels(
                [str(lead) for lead in LEADS]
            )

            ax.set_yticks(
                np.arange(len(WINDOW_SIZES))
            )

            ax.set_yticklabels(
                window_labels
            )

            if row == 0:
                ax.set_title(
                    experiment_label,
                    fontsize=13,
                    fontweight="bold",
                )

            if col == 0:
                ax.set_ylabel(
                    "Neighborhood size",
                    fontsize=10,
                )

                ax.text(
                    -0.38,
                    0.5,
                    (
                        f"{format_threshold(threshold)} "
                        "mm / 24 h"
                    ),
                    transform=ax.transAxes,
                    rotation=90,
                    va="center",
                    ha="center",
                    fontsize=11,
                    fontweight="bold",
                )

            if row == len(THRESHOLDS) - 1:
                ax.set_xlabel(
                    "Lead time (h)",
                    fontsize=11,
                )

            ax.tick_params(
                axis="both",
                labelsize=9,
            )

    fig.suptitle(
        (
            f"FSS | {EXPERIMENT_CTL_LABEL} vs {EXPERIMENT_NEW_LABEL} | {reference}\n"
            "24-h accumulated precipitation"
        ),
        fontsize=15,
        y=0.995,
    )

    fig.subplots_adjust(
        left=0.16,
        right=0.88,
        bottom=0.06,
        top=0.95,
        hspace=0.22,
        wspace=0.12,
    )

    cbar_ax = fig.add_axes(
        [0.91, 0.15, 0.018, 0.70]
    )

    cbar = fig.colorbar(
        last_im,
        cax=cbar_ax,
        ticks=np.arange(0.0, 1.01, 0.1),
    )

    cbar.set_label(
        "Fractions Skill Score (FSS)",
        fontsize=11,
    )

    output = (
        Path(output_dir)
        / f"FSS_{EXPERIMENT_CTL_LABEL}_vs_{EXPERIMENT_NEW_LABEL}_{reference}.png"
    )

    fig.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(f"Saved: {output}")


# ============================================================
# Plot 2: Delta FSS = NEW - CTL
# ============================================================

def plot_delta_fss(comparison, reference, output_dir):
    """
    Plot Delta FSS = FSS_NEW - FSS_CTL.

    Positive values:
        FSS_NEW > FSS_CTL

    Negative values:
        FSS_NEW < FSS_CTL

    The colour scale is symmetric around zero.
    """

    delta_values = comparison["delta_fss"].to_numpy()

    finite_delta = delta_values[
        np.isfinite(delta_values)
    ]

    if finite_delta.size == 0:
        raise ValueError(
            f"No finite Delta FSS values for {reference}."
        )

    if DELTA_LIMIT is None:

        delta_limit = float(
            np.nanmax(np.abs(finite_delta))
        )

        # Avoid a zero-width colour scale.
        if delta_limit == 0.0:
            delta_limit = 0.01

        # Round upward to a convenient 0.01 interval.
        delta_limit = (
            np.ceil(delta_limit * 100.0)
            / 100.0
        )

    else:
        delta_limit = float(DELTA_LIMIT)

    delta_norm = TwoSlopeNorm(
        vmin=-delta_limit,
        vcenter=0.0,
        vmax=delta_limit,
    )

    delta_ticks = np.linspace(
        -delta_limit,
        delta_limit,
        9,
    )

    fig, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(15, 9),
        sharex=True,
        sharey=True,
    )

    axes = axes.ravel()

    window_labels = get_window_labels(comparison)

    last_im = None

    for ax, threshold in zip(
        axes,
        THRESHOLDS,
    ):

        matrix = make_matrix(
            comparison,
            threshold,
            "delta_fss",
        )

        last_im = ax.imshow(
            matrix.to_numpy(),
            origin="lower",
            aspect="auto",
            cmap=CMAP_DELTA,
            norm=delta_norm,
            interpolation="nearest",
        )

        ax.set_title(
            (
                f"Threshold = "
                f"{format_threshold(threshold)} mm / 24 h"
            ),
            fontsize=11,
        )

        ax.set_xticks(
            np.arange(len(LEADS))
        )

        ax.set_xticklabels(
            [str(lead) for lead in LEADS]
        )

        ax.set_yticks(
            np.arange(len(WINDOW_SIZES))
        )

        ax.set_yticklabels(
            window_labels
        )

        ax.set_xlabel(
            "Lead time (h)"
        )

        ax.set_ylabel(
            "Neighborhood size"
        )

        # Mark the zero contour when it crosses the panel.
        values = matrix.to_numpy()

        finite = values[np.isfinite(values)]

        if (
            finite.size > 0
            and np.nanmin(finite) <= 0.0
            and np.nanmax(finite) >= 0.0
        ):
            try:
                ax.contour(
                    np.arange(len(LEADS)),
                    np.arange(len(WINDOW_SIZES)),
                    values,
                    levels=[0.0],
                    colors="black",
                    linewidths=0.8,
                    linestyles="--",

                )
            except ValueError:
                pass

    fig.suptitle(
        (
            f"Delta FSS = {EXPERIMENT_NEW_LABEL} - {EXPERIMENT_CTL_LABEL} | {reference}\n"
            "24-h accumulated precipitation"
        ),
        fontsize=15,
        y=0.98,
    )

    fig.subplots_adjust(
        left=0.10,
        right=0.88,
        bottom=0.10,
        top=0.89,
        hspace=0.28,
        wspace=0.22,
    )

    cbar_ax = fig.add_axes(
        [0.91, 0.16, 0.018, 0.66]
    )

    cbar = fig.colorbar(
        last_im,
        cax=cbar_ax,
        ticks=delta_ticks,
        extend="both",
    )

    cbar.ax.set_yticklabels(
        [f"{value:.3f}" for value in delta_ticks]
    )

    cbar.set_label(
        f"Delta FSS ({EXPERIMENT_NEW_LABEL} - {EXPERIMENT_CTL_LABEL})",
        fontsize=11,
    )

    output = (
        Path(output_dir)
        / f"Delta_FSS_{EXPERIMENT_NEW_LABEL}_minus_{EXPERIMENT_CTL_LABEL}_{reference}.png"
    )

    fig.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(f"Saved: {output}")

    return delta_limit


# ============================================================
# Main
# ============================================================

def main():

    args = parse_args()

    base_dir = Path(args.base_dir)
    output_dir = Path(args.output_dir)

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    references = select_references(
        args.references
    )

    print("")
    print("=" * 70)
    print("FSS plotting: ")
    print("=" * 70)
    print(f"Input directory : {base_dir}")
    print(f"Output directory: {output_dir}")
    print(
        "References      : "
        + ", ".join(references)
    )
    print("")

    for reference in references:

        print("-" * 70)
        print(f"Reference: {reference}")

        ctl_file = find_aggregate_file(
            base_dir,
            EXPERIMENT_CTL,
            reference,
        )

        new_file = find_aggregate_file(
            base_dir,
            EXPERIMENT_NEW,
            reference,
        )

        print(f"CTL: {ctl_file}")
        print(f"NEW: {new_file}")

        df_ctl = read_aggregate_csv(
            ctl_file
        )

        df_new = read_aggregate_csv(
            new_file
        )

        validate_expected_structure(
            df_ctl,
            EXPERIMENT_CTL,
            reference,
        )

        validate_expected_structure(
            df_new,
            EXPERIMENT_NEW,
            reference,
        )

        validate_processing_status(
            df_ctl,
            EXPERIMENT_CTL,
            reference,
        )

        validate_processing_status(
            df_new,
            EXPERIMENT_NEW,
            reference,
        )

        comparison = prepare_comparison(
            df_ctl,
            df_new,
            reference,
        )

        print(
            "Validated combinations: "
            f"{len(comparison)}"
        )

        print(
            "Valid cases per combination: "
            f"{sorted(comparison['n_valid_cases'].unique())}"
        )

        delta_min = comparison[
            "delta_fss"
        ].min()

        delta_max = comparison[
            "delta_fss"
        ].max()

        print(
            f"Delta FSS range: "
            f"{delta_min:+.4f} to "
            f"{delta_max:+.4f}"
        )

        reference_output_dir = (
            output_dir
            / reference
        )

        reference_output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        plot_ctl_new(
            comparison,
            reference,
            reference_output_dir,
        )

        delta_limit = plot_delta_fss(
            comparison,
            reference,
            reference_output_dir,
        )

        print(
            f"Delta colour scale: "
            f"{-delta_limit:+.2f} to "
            f"{delta_limit:+.2f}"
        )

        print("")

    print("=" * 70)
    print("Figures generated successfully.")
    print("=" * 70)


if __name__ == "__main__":
    main()